# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balengou', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbacklog',
            options={'verbose_name': 'Backlog de Produit', 'verbose_name_plural': 'Backlog des produits'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'verbose_name': 'Itération', 'verbose_name_plural': 'Itérations'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
        migrations.AlterModelOptions(
            name='userstory',
            options={'verbose_name': 'Demande client', 'verbose_name_plural': 'Demandes client'},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='member',
            new_name='members',
        ),
    ]
